### ISSUE TITLE
WebHook throws an error 500, if the JSON exceeds 102400 bytes

### ISSUE THREAD

**Issue by idmedia-kaiser** [contentstack/webhook-listener#13]
If an entry contains more then 102400 bytes of data, the web hook fails to parse the JSON
`{
  "message": "Request failed with status code 500",
  "statusCode": 500,
  "code": "ERR_BAD_RESPONSE",
  "body": {
    "error": {
      "message": {
        "message": "request entity too large",
        "expected": 104096,
        "length": 104096,
        "limit": 102400,
        "type": "entity.too.large"
      }
    }
  }
}`

After some analysis of the web hook we found that the bodyParser.json() is not  configurable via config parameters.
Which means that the default limit is set here which is 100kb according to the bodyParser documentation
https://www.npmjs.com/package/body-parser
**_limit**
Controls the maximum request body size. If this is a number, then the value specifies the number of bytes; if it is a string, the value is passed to the [bytes](https://www.npmjs.com/package/bytes) library for parsing. Defaults to '100kb'_

Can you please make this configurable via env or config parameter or set a higher default value for the "limit" of the body parser

**Comment by netrajpatel** [comment]
Hi @idmedia-kaiser,
We have noted this issue and the team will look into this issue.
Thank you!

**Comment by vkalta** [comment]
Hi @idmedia-kaiser , is it possible to get access to the stack in order to reproduce this issue?

**Comment by vkalta** [comment]
Hi @idmedia-kaiser , a new config parameter is added to address this issue i.e. "reqBodyLimit". Please check and confirm.
Thanks

**Comment by netrajpatel** [comment]
The issue has been resolved hence closing this ticket.
